### ISSUE TITLE
ValueError: None values not supported.

### ISSUE THREAD

**Issue by woreom** [anhtuhsp/FaceRecognition#6]
when you run the train_softmax.py first it raises categorical_feature is not define then when you fix it with columntransformer, it raises ValueError

**Comment by woreom** [comment]
you have to change the optimizer in the model in order to fix this problem

**Comment by haivmptit** [comment]
> you have to change the optimizer in the model in order to fix this problem

Hi you, can you tell me How to change, please ?

**Comment by woreom** [comment]
I think I meant sth like this in `softmax.py`
```
optimizer = Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
        model.compile(loss=keras.losses.categorical_crossentropy,
                      optimizer=optimizer,
                      metrics=['accuracy'])
```
